version: '3.8'
services:
  api:
    build: .
    container_name: my-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: .env
    depends_on:
      - mongodb
    restart: always
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: npm run dev
  
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

    restart: always

volumes:
  ignore :
  mongodb_data:
